"""faq entries and knowledge source name

Revision ID: 0e32c1d21f8a
Revises: f123fc515e83
Create Date: 2026-08-29 19:40:46.835733

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0e32c1d21f8a'
down_revision: str | Sequence[str] | None = 'f123fc515e83'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq_entries',
    sa.Column('knowledge_source_id', sa.UUID(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_entries_knowledge_source_id'), 'faq_entries', ['knowledge_source_id'], unique=False)
    op.add_column('knowledge_sources', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_sources', 'name')
    op.drop_index(op.f('ix_faq_entries_knowledge_source_id'), table_name='faq_entries')
    op.drop_table('faq_entries')
    # ### end Alembic commands ###
