"""prompt versions

Revision ID: 67633a31b19a
Revises: 4289d8f102a6
Create Date: 2026-08-29 14:34:50.167639

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '67633a31b19a'
down_revision: str | Sequence[str] | None = '4289d8f102a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('prompt_template_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_template_id', 'version', name='uq_prompt_versions_prompt_template_version')
    )
    op.create_index(op.f('ix_prompt_versions_prompt_template_id'), 'prompt_versions', ['prompt_template_id'], unique=False)
    op.add_column('prompt_templates', sa.Column('current_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key('fk_prompt_templates_current_version_id', 'prompt_templates', 'prompt_versions', ['current_version_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_prompt_templates_current_version_id', 'prompt_templates', type_='foreignkey')
    op.drop_column('prompt_templates', 'current_version_id')
    op.drop_index(op.f('ix_prompt_versions_prompt_template_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
