"""assistant version prompt reference

Revision ID: 71d607abbe1c
Revises: 67633a31b19a
Create Date: 2026-08-29 14:58:42.131150

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '71d607abbe1c'
down_revision: str | Sequence[str] | None = '67633a31b19a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_versions', sa.Column('prompt_template_id', sa.UUID(), nullable=True))
    op.add_column('assistant_versions', sa.Column('prompt_version', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_assistant_versions_prompt_template_id', 'assistant_versions', 'prompt_templates', ['prompt_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_assistant_versions_prompt_template_id', 'assistant_versions', type_='foreignkey')
    op.drop_column('assistant_versions', 'prompt_version')
    op.drop_column('assistant_versions', 'prompt_template_id')
    # ### end Alembic commands ###
