"""knowledge source and chunk assistant scoping

Revision ID: 875b5df3ae33
Revises: b1382c92d157
Create Date: 2026-08-31 13:49:08.192057

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '875b5df3ae33'
down_revision: str | Sequence[str] | None = 'b1382c92d157'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('assistant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_chunks_assistant_id'), 'chunks', ['assistant_id'], unique=False)
    op.create_foreign_key(
        'fk_chunks_assistant_id', 'chunks', 'assistants', ['assistant_id'], ['id'], ondelete='CASCADE'
    )
    op.add_column('knowledge_sources', sa.Column('assistant_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_knowledge_sources_assistant_id'), 'knowledge_sources', ['assistant_id'], unique=False)
    op.create_foreign_key(
        'fk_knowledge_sources_assistant_id',
        'knowledge_sources',
        'assistants',
        ['assistant_id'],
        ['id'],
        ondelete='CASCADE',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_knowledge_sources_assistant_id', 'knowledge_sources', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_sources_assistant_id'), table_name='knowledge_sources')
    op.drop_column('knowledge_sources', 'assistant_id')
    op.drop_constraint('fk_chunks_assistant_id', 'chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chunks_assistant_id'), table_name='chunks')
    op.drop_column('chunks', 'assistant_id')
    # ### end Alembic commands ###
