"""glossary entries

Revision ID: 8931e4e136d7
Revises: 71d607abbe1c
Create Date: 2026-08-29 16:33:19.104848

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8931e4e136d7'
down_revision: str | Sequence[str] | None = '71d607abbe1c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('glossary_entries',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('assistant_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.Column('phonetic_spelling', sa.String(length=255), nullable=True),
    sa.Column('stt_boost_weight', sa.Numeric(precision=3, scale=2, asdecimal=False), server_default=sa.text('0.5'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assistant_id', 'term', name='uq_glossary_entries_assistant_term')
    )
    op.create_index(op.f('ix_glossary_entries_assistant_id'), 'glossary_entries', ['assistant_id'], unique=False)
    op.create_index(op.f('ix_glossary_entries_organization_id'), 'glossary_entries', ['organization_id'], unique=False)
    op.create_index(op.f('ix_glossary_entries_workspace_id'), 'glossary_entries', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_glossary_entries_workspace_id'), table_name='glossary_entries')
    op.drop_index(op.f('ix_glossary_entries_organization_id'), table_name='glossary_entries')
    op.drop_index(op.f('ix_glossary_entries_assistant_id'), table_name='glossary_entries')
    op.drop_table('glossary_entries')
    # ### end Alembic commands ###
