"""assistant versions

Revision ID: a9c2aadaa88d
Revises: e196da966c0e
Create Date: 2026-08-29 10:26:34.769304

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a9c2aadaa88d'
down_revision: str | Sequence[str] | None = 'e196da966c0e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_versions',
    sa.Column('assistant_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('voice_id', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('greeting', sa.Text(), nullable=False),
    sa.Column('persona', sa.Text(), nullable=True),
    sa.Column('speech_rate', sa.Numeric(precision=3, scale=2, asdecimal=False), nullable=False),
    sa.Column('turn_sensitivity', sa.Numeric(precision=3, scale=2, asdecimal=False), nullable=False),
    sa.Column('creativity', sa.Numeric(precision=3, scale=2, asdecimal=False), nullable=False),
    sa.Column('ambient_sound', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assistant_id', 'version', name='uq_assistant_versions_assistant_version')
    )
    op.create_index(op.f('ix_assistant_versions_assistant_id'), 'assistant_versions', ['assistant_id'], unique=False)
    op.add_column('assistants', sa.Column('current_version_id', sa.UUID(), nullable=True))
    op.create_foreign_key(
        'fk_assistants_current_version_id',
        'assistants',
        'assistant_versions',
        ['current_version_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_assistants_current_version_id',
        'assistants',
        type_='foreignkey',
    )
    op.drop_column('assistants', 'current_version_id')
    op.drop_index(op.f('ix_assistant_versions_assistant_id'), table_name='assistant_versions')
    op.drop_table('assistant_versions')
    # ### end Alembic commands ###
