"""assistant version call and recording settings

Revision ID: b1382c92d157
Revises: 3de09a4cc4b3
Create Date: 2026-08-31 13:09:50.965008

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b1382c92d157'
down_revision: str | Sequence[str] | None = '3de09a4cc4b3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistant_versions', sa.Column('ambient_sound_volume', sa.Numeric(precision=3, scale=2, asdecimal=False), nullable=True))
    op.add_column('assistant_versions', sa.Column('max_call_duration_seconds', sa.Integer(), nullable=True))
    op.add_column('assistant_versions', sa.Column('max_silence_timeout_seconds', sa.Integer(), nullable=True))
    op.add_column('assistant_versions', sa.Column('record_calls', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('assistant_versions', sa.Column('auto_delete_on_declined_consent', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assistant_versions', 'auto_delete_on_declined_consent')
    op.drop_column('assistant_versions', 'record_calls')
    op.drop_column('assistant_versions', 'max_silence_timeout_seconds')
    op.drop_column('assistant_versions', 'max_call_duration_seconds')
    op.drop_column('assistant_versions', 'ambient_sound_volume')
    # ### end Alembic commands ###
