"""crawled pages and knowledge source url

Revision ID: f123fc515e83
Revises: 45080fdf818f
Create Date: 2026-08-29 19:13:18.193710

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f123fc515e83'
down_revision: str | Sequence[str] | None = '45080fdf818f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawled_pages',
    sa.Column('knowledge_source_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('knowledge_source_id', 'url', name='uq_crawled_pages_knowledge_source_url')
    )
    op.create_index(op.f('ix_crawled_pages_knowledge_source_id'), 'crawled_pages', ['knowledge_source_id'], unique=False)
    op.add_column('knowledge_sources', sa.Column('source_url', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_sources', 'source_url')
    op.drop_index(op.f('ix_crawled_pages_knowledge_source_id'), table_name='crawled_pages')
    op.drop_table('crawled_pages')
    # ### end Alembic commands ###
