"""one pending invitation per address

Revision ID: f581c9da6b72
Revises: 09797a6b1627
Create Date: 2026-08-26 13:30:43.334173

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f581c9da6b72'
down_revision: str | Sequence[str] | None = '09797a6b1627'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_invitations_pending_org_email', 'invitations', ['organization_id', 'email'], unique=True, postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_invitations_pending_org_email', table_name='invitations', postgresql_where=sa.text("status = 'pending'"))
    # ### end Alembic commands ###
